# -*- mode: ruby -*-
# vi: set ft=ruby :
RUBY_MAJOR="1.9"
RUBY_VERSION="1.9.3-p547"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.ssh.insert_key = true
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y psmisc git build-essential tzdata \
    apt-transport-https ca-certificates software-properties-common language-pack-en locales \
    libtool autoconf libtcmalloc-minimal4
    #echo "Asia/Taipei" | tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
    sudo timedatectl set-timezone Asia/Taipei
    apt-get clean #&& rm -rf /var/lib/apt/lists/*
    export GEM_HOME="/opt/rubies/ruby-1.9.3-p547"

    mkdir /usr/src
    # Ruby-1.9.3
    wget https://github.com/RubyClickAP/ruby-install/archive/v0.4.3.tar.gz
    tar -xzvf v0.4.3.tar.gz -C /usr/src/
    cd /usr/src/ruby-install-0.4.3/ && make install
    ruby-install -p https://gist.github.com/RubyClickAP/2870213e303a98de07216305949f615f/raw/74b8d615550d46a865921ccc8391fd02b01d2de8/railsexpress-1.9.3-p547.patch ruby 1.9.3-p547 -- --enable-shared CFLAGS="-O3"
    #sudo chmod go-w -R /opt/rubies/ruby-1.9.3-p547/bin
    # Test 14March2019, done.
    echo "export GEM_HOME=/opt/rubies/ruby-1.9.3-p547" >> /home/vagrant/.bashrc
    echo "export PATH=/opt/rubies/ruby-1.9.3-p547/bin:$PATH" >> /home/vagrant/.bashrc
    #source ~/bashrc
    echo "*** Ruby 1.9 successfully installed."
  SHELL

  $componet_install_script = <<-SCRIPT
    export PATH=/opt/rubies/ruby-1.9.3-p547/bin:$PATH
    cd /usr/src
    gem install --no-ri --no-rdoc monk
    #Ruby-Passenger
    gem install --no-ri --no-rdoc bundler -v 1.17.3
    gem install --no-ri --no-rdoc rack -v 1.6.11
    gem install --no-ri --no-rdoc passenger
    #Other gem
    gem install --no-ri --no-rdoc activesupport -v 4.2.6
    gem install --no-ri --no-rdoc mime-types -v 2.99.3
    gem install --no-ri --no-rdoc unix-crypt -v 1.3.0
    #mono_logger
    gem install mono_logger --no-ri --no-rdoc  -v 1.1.0
    gem install multi_json --no-ri --no-rdoc  -v 1.11.2
    gem install tilt  --no-ri --no-rdoc -v 1.4.1
SCRIPT

  config.vm.define "ruby193" do|ruby193|
    ruby193.vm.provision :shell, inline: <<-SHELL
      #echo "Current user: [`whoami`], deal with Gem..."
      sudo /bin/bash << 'SCRIPT'
        echo "Current user: [`whoami`], deal with SUDO script..."
        echo "*** done."
SCRIPT
      sudo apt-get clean
      sudo dd if=/dev/zero of=/EMPTY bs=1M
      sudo rm -f /EMPTY
      cat /dev/null > ~/.bash_history && history -c && exit
      echo "*** vagrant package --output ruby193.box"
      echo "*** vagrant box add ruby193 ruby193.box"
      cd /usr/src/app
    SHELL
    #ruby193.vm.provision :shell, privileged: true, inline: $componet_install_script
  end
end
